#!/bin/bash
### BEGIN INIT INFO
# Provides:          amonnpm
# Description:       Amon package manager - installs plugins.

AGENTPATH='/usr/bin/amon-agent.py'
PLUGIN_PATH="/etc/amonagent/plugins"
PLUGINS_ENABLED="$PLUGIN_PATH/plugins-enabled"
AGENTUSER="amonagent"

function file_exists() {
    [ -f "$1" ]
}

# Root user detection
if [ $(echo "$UID") = "0" ]; then
    sudo_cmd=''
else
    sudo_cmd='sudo'
fi

[ -f $AGENTPATH ] || echo "$AGENTPATH not found"

action=$1

case $action in
        

    install)
        $0 update
        PLAYBOOK="$PLUGIN_PATH/$2/$2.yml"
        
        if file_exists $PLAYBOOK ; then
             $sudo_cmd sh -c "ansible-playbook $PLAYBOOK -i /etc/amonagent/plugins/hosts"
        else
             printf "\033[31m \n Cant find a plugin named $2\n\033[0m\n"
             printf "\033[32m Available plugins: \n\033[0m\n"
             $sudo_cmd ls -l $PLUGIN_PATH --time-style='long-iso' | grep '^d' | awk '{print $8}'
        fi
        su $AGENTUSER -c "python $AGENTPATH restart"
        exit $?
        ;;

    test)
        su $AGENTUSER -c "python $AGENTPATH test_plugins"
        exit $?
        ;;

    uninstall)
        CONFIGURATION_FILE="$PLUGINS_ENABLED/$2.conf"
        $sudo_cmd rm -rf  CONFIGURATION_FILE
        su $AGENTUSER -c "python $AGENTPATH restart"
        exit $?
        ;;

    update)
        su $AGENTUSER -c "(cd $PLUGIN_PATH && git pull origin master)"
        exit $?
        ;;

    *)
        echo "Usage: $0 {install|test|update|uninstall}"
        exit 2
        ;;
esac
