#! /bin/bash

set -e

case "$1" in
    configure)
        update-rc.d amon-agent defaults
        adduser --system amonagent --disabled-login --shell /bin/sh --no-create-home --quiet
        chown root:root /etc/init.d/amon-agent
        chown -R amon-agent:root /etc/amon-agent
        chown -R amon-agent:root /var/log/amonagent

        set +e

        if which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d amon-agent restart
        else
            /etc/init.d/amon-agent restart
        fi

        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
          if [ $RETVAL -eq 3 ]; then
            # No amonagent.conf file is present. The user is probably following
            # the step-by-step instructions and will add the config file next.
            exit 0
          else
            exit $?
          fi
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
