#! /bin/sh

if [ "$1" = purge ]; then
    update-rc.d amon-agent remove -f || true 
	getent passwd amonagent >/dev/null && deluser amonagent
	getent group  amonagent >/dev/null && groupdel amonagent
	rm -rf /var/log/amonagent
	rm -rf /etc/amonagent
fi

/usr/bin/yes | pip uninstall amonagent || true

exit 0
