#! /bin/bash
PLUGINS_REPO=/etc/amonagent/plugins
REMOTE_REPO=https://github.com/amonapp/amon-plugins.git

set -e

case "$1" in
    configure)
       
        update-rc.d amon-agent defaults
        getent group amonagent >/dev/null || groupadd amonagent -f
        getent passwd amonagent >/dev/null || \
            useradd -r -M -g amonagent -s /bin/sh -c "Amon Agent" amonagent
        
        
        chown amonagent:amonagent /etc/init.d/amon-agent
        chown amonagent:amonagent /usr/bin/amonpm
        chown amonagent:amonagent /var/run/amonagent
        
        chown -R amonagent:amonagent /var/log/amonagent

 
        LOCALREPO_VC_DIR=$PLUGINS_REPO/.git

        rm -rf $PLUGINS_REPO
        git clone $REMOTE_REPO $PLUGINS_REPO
        
        chown -R amonagent:amonagent /etc/amonagent
        set +e


        curl --insecure --silent --show-error --retry 5 -L https://bootstrap.pypa.io/ez_setup.py -o - | python
        curl --insecure --silent --show-error --retry 5 -L https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py | python
        pip install https://github.com/amonapp/amonagent/archive/master.zip

        /etc/init.d/amon-agent restart

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
