FROM centos:latest
MAINTAINER Martin Rusev

ADD amon.repo /etc/yum.repos.d/amon.repo

RUN yum -t -y install amon-agent

RUN /etc/init.d/amon-agent status
RUN /etc/init.d/amon-agent test_collectors
RUN /etc/init.d/amon-agent test_plugins
RUN ls -lh /etc/amonagent/plugins

CMD ["/bin/bash"]